### ISSUE TITLE
Docker push step automatically tags image with latest even when tags are set

### ISSUE THREAD

**Issue by faiq** [wercker/wercker#104]
Suppose you have a pipeline like this

```
push:
    box:
        id: alpine
        cmd: /bin/sh
    steps:
        - internal/docker-push:
            username: $UNAME
            password: $PWORD
            tag: test, staging
            repository: quay.io/wercker/test-faiq
            registry: https://quay.io
```

you would expect the only 2 tags associated with your image should be `test` and `staging`, but a third tag `latest` appears as well when you run the pipeline. 

This happened as a result of #85 we took out the `Tag` option when we commit the container, and when that happens the tag `latest` is automatically assigned. To fix, I'll add `s.tags[0]` when doing the commit.
