### ISSUE TITLE
chained workflow runs: source-dir broken

### ISSUE THREAD

**Issue by flenter** [wercker/wercker#151]
As a test I created a small test repository with a test.txt in the src folder.

And the following wercker.yml:
```
source-dir: src
box: node:0.10
build:
    steps:
        - script:
            code: |
                cat test.txt

next:
    steps:
        - script:
            code: |
                cat test.txt

final:
    steps:
        - script:
            code: |
                cat test.txt
```

The final run will fail during the wercker-init step and in the debug data of the run I can see:
`/bin/bash: line 46: cd: /pipeline/source/src: No such file or directory`

**Comment by flenter** [comment]
A workaround for this is to maintain a 'src' directory in the output like so: 
```
source-dir: src
box: node:0.10
build:
    steps:
        - script:
            code: |
                pwd
                cat test.txt

next:
    steps:
        - script:
            code: |
                cat test.txt
                mv $WERCKER_ROOT/src $WERCKER_OUTPUT_DIR

final:
    steps:
        - script:
            code: |
                cat test.txt
                mv $WERCKER_ROOT/src $WERCKER_OUTPUT_DIR
```
