### ISSUE TITLE
Add support for separate box per deploy pipeline

### ISSUE THREAD

**Issue by mitel** [wercker/wercker#152]
Use case with multi deploy targets: deploy to docker-hub using a clean docker image, without curl, npm etc; then deploy to Marathon from a different box where curl is needed.

**Comment by mwhooker** [comment]
Hi @mitel,

hope this answers your question. You can specify the box for each pipeline by adding a `box` field. For example, the way we deploy an internal project looks a little like this

```yaml
<snip>
deploy-kube:
    box:
      id: <docker image name>
      username: $DOCKER_USER
      password: $DOCKER_PASSWORD
      registry: https://quay.io
      tag: $WERCKER_GIT_BRANCH-$WERCKER_GIT_COMMIT
      cmd: /bin/sh
    steps:
        <snip>

push-quay:
    box:
        id: alpine
        cmd: /bin/sh
    steps:
        <snip>
```

if this isn't the answer you're looking for, please reopen.

**Comment by mitel** [comment]
Hello @mwhooker ,
the docs are not very clear on the complete syntax. 

this one will give me an error: `No pipeline named deploy`
```yml
deploy:
  target1:
    box:
      <snip>
    steps:
      <snip>
  target2:
    box:
      <snip>
    steps:
      <snip>
```

this one works, but then i can't specify the box (it follows the docs from [http://devcenter.wercker.com/docs/deploy/multi-deploy-targets.html](url))
```yml
deploy:
  target1:
    - script:
      <snip>
    - script:
      <snip>
  target2:
    - script:
      <snip>
    - script:
      <snip>
```
