### ISSUE TITLE
kube-initialize fails without error output

### ISSUE THREAD

**Issue by otaviosoares** [wercker/wercker#174]
I'm deploying a test app to a kubernetes cluster (using workflows for the first time). However, after my image has been created and pushed the kube-initialize command fails silently. Before even getting the code. 
![gecodefailed](https://cloud.githubusercontent.com/assets/180912/15610572/461c06a8-23fc-11e6-8f31-1a78a974bad1.png)

![Error image](https://cloud.githubusercontent.com/assets/180912/15563479/52dba1be-22df-11e6-95a1-4c3bd7b67655.png)

Here's the wercker.yml piece:

```yml
kube-initialize:
  steps:        
    - kubectl:
      server: $KUBERNETES_MASTER
      username: $KUBERNETES_USERNAME
      password: $KUBERNETES_PASSWORD
      insecure-skip-tls-verify: true
      command: create -f specs/kube-controller.yaml

    - kubectl:
      server: $KUBERNETES_MASTER
      username: $KUBERNETES_USERNAME
      password: $KUBERNETES_PASSWORD
      insecure-skip-tls-verify: true
      command: create -f specs/kube-service.yaml
```

Am I missing something?

Thank you
