### ISSUE TITLE
wercker should not inject a cmd when entrypoint is used

### ISSUE THREAD

**Issue by hatchan** [wercker/wercker#218]
Currently we inject `/bin/bash` when no `cmd` is provided for a box. This behavior is not desired when overriding the entrypoint (if the container provides an alternative entrypoint):

```
push-quay:
  box:
    id: quay.io/wercker/cronetes
    entrypoint: /bin/sh
```

See https://github.com/wercker/wercker/blob/master/docker/box.go#L87-L92

**Comment by hatchan** [comment]
Workaround:

```
push-quay:
  box:
    id: quay.io/wercker/cronetes
    entrypoint: /bin/sh -c
    cmd: /bin/sh
```
