### ISSUE TITLE
pushing multiple tags to ECR does not work

### ISSUE THREAD

**Issue by mies** [wercker/wercker#220]
@faiq please fix this

**Comment by hatchan** [comment]
Just to confirm that this is working for a "normal" push to quay (cronetes pushes to `branch+commit`, and `latest`. 

Be sure to double check ECR to see if they werent created there. I've seen some conflicting statements in the docker push logs on wercker on occasion.

**Comment by yanivtal** [comment]
Not working for me with Docker Hub. No matter what I do there's only a single "latest" tag applied. I've tried setting multiple tags with the tag and tags key.

**Comment by faiq** [comment]
@yanivtal would you mind pasting your yaml here so i can take a look?

**Comment by pogo19** [comment]
Wercker support asked me to send my wercker file contents to this issue to help support fixing it. Here comes the critical part.

```yaml
- internal/docker-scratch-push:
            tag: ${WERCKER_GIT_COMMIT} ${APP_VERSION}
            volumes: /opt/app-unzipped
            disable-sync: true
            author: <app author>
            aws-access-key: ${ECR_ACCESS_KEY_ID}
            aws-secret-key: ${ECR_SECRET_ACCESS_KEY}
            aws-region: us-east-1
            aws-registry-id: <registry id>
            repository: app/controller
```

Some parts were omitted due to confidentiality issues. ${APP_VERSION} is something like 1.5.10 or 1.5.11-beta1. Also this format of tag is not supported even when it is the only tag given.

Full wercker file contains some more confidential data but it is available to wercker support (support access is enabled).
