### ISSUE TITLE
Race condition in getting envvars in preperation for internal docker push

### ISSUE THREAD

**Issue by nhumrich** [wercker/wercker#226]
The internal docker push section has a race condition in getting environment variables.

If I have the following wercker file, I can most of the time deploy to dockerhub correctly, however, every once in a while, it gets deployed to "latest" instead of the tag I specify. This tells me that wercker has a race condition, and every once in a while is not correctly reading the environment variables.

``` yaml
dockerhub:
  steps:
    - script:
        name: get tags
        code: |
            export DOCKER_TAG="$(cat version.tag)"
    - internal/docker-push:
          repository: $REPO
          tag: $DOCKER_TAG
          ports: ["80"]
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD
          cmd: /sbin/my_init
          ports: ["80"]
```

**Comment by Platane** [comment]
Hi, same thing here.

I create this to reproduce :
https://github.com/Platane/wercker-push-test

It fails all the time to push the correct tag, I always got 'latest' instead.

This happens only when I use linux alpine box.

**Comment by nhumrich** [comment]
I also use alpine, but I patch the container to have the proper --null option on the env command https://github.com/CanopyTax/alpine

**Comment by faiq** [comment]
Thanks for opening up the issue, and sorry for the late response! I'm to close it now, as it seems resolved. Feel free to reopen if you have more thoughts or comments on this issue!

**Comment by nhumrich** [comment]
@faiq can you explain how this issue is resolved?

**Comment by followbl** [comment]
@nhumrich what did you end up doing to workaround this? I'm running in to the exact same thing :(

**Comment by nhumrich** [comment]
@followbl I didnt. I never did fix the issue and @faiq never mentioned how it got fixed or how they verified a fix. This thread just became inactive when there was no response from wercker, and I myself cant just reopen. I just had to stop using custom env vars like $DOCKER_TAG which I really dont like.

**Comment by followbl** [comment]
thanks for the response @nhumrich ...I was speaking with @riceo in slack today about getting this looked @

We're looking in to moving over from travis, but this would be a deal breaker for us as we have a pretty specific tagging strategy. I'll definitely keep you posted if I hear anything 👍

**Comment by faiq** [comment]
@nhumrich from my understanding it was an issue with syncing envvars to alpine. i also thought when you said you built the container this way, the issue went away.

> I also use alpine, but I patch the container to have the proper --null option on the env command https://github.com/CanopyTax/alpine
 
i'll reopen again. sorry for the misunderstanding

**Comment by followbl** [comment]
@faiq to offer a little help, I tried the env --null option yesterday and didn't have any luck...Happy to help debugging on any of my builds if you'd like

**Comment by nhumrich** [comment]
@faiq the patch comment was a response to Platane. Glad this issue is re-opened.

**Comment by AdrienFromToulouse** [comment]
Any updates?

I am facing the same issue I think.

```yml
deploy-to-ecr:
  box: adrienfromtoulouse/ubuntu14-ffmpeg
  steps:
    - install-packages:
        packages: jq
    - script:
        name: prepare docker push
        code: |
          ./scripts/docker-push.sh
          echo "REGION $REGION"
    - internal/docker-push:
        disable-sync: true
        aws-access-key: $AWS_ACCESS_KEY
        aws-secret-key: $AWS_SECRET_KEY
        aws-region: $REGION
        aws-registry-id: $AWS_TEST_ACCOUNT_ID
        repository: $ECR_REPOSITORY
        tag: $TAG
        working-dir: $WORKING_DIR
        cmd: $CMD
```

All is perfectly at the script step level however the exported variables are not accessible by the internal docker push step. 

Any thoughts?
