### ISSUE TITLE
after-steps does not work completely.

### ISSUE THREAD

**Issue by harukaeru** [wercker/wercker#256]
`after-steps` in `build` have not work completely since 15 days ago.
We don't change codes of wercker.yml.

This is our `wercker.yml`

``` yaml
command-timeout: 60
build:
    steps:
        - script:
            name: source ~/.bashrc and python environment
            code: |
                source ~/.bashrc
                echo "python version $(python --version) running"
                echo "pip version $(pip --version) running"
                echo "PIP_DOWNLOAD_CACHE=$WERCKER_CACHE_DIR/pip-download-cache"
                export PIP_DOWNLOAD_CACHE=$WERCKER_CACHE_DIR/pip-download-cache
                export PIP_WHEEL_DIR=$WERCKER_CACHE_DIR/pip-wheels
                echo "PIP_FIND_LINKS=$WERCKER_CACHE_DIR/pip-wheels"
                export PIP_FIND_LINKS=$WERCKER_CACHE_DIR/pip-wheels
                export PIP_USE_WHEEL=true

        - pip-install:
            requirements_file: "requirements/test.txt" # Optional argument.

        - script:
            name: create mysql database
            code: |
                echo 'create database `g3-test` default character set utf8;grant all privileges on *.* to `g3-user`@"localhost" identified by "$PASSWORD" with grant option'| mysql -u root

        - script:
            name: execute flake8
            code: |
                flake8 ../source

        - script:
            name: execute test
            code: |
                pip install coverage coveralls
                export DJANGO_SETTINGS_MODULE=goocus.settings.test
                coverage run manage.py test -v 2
                coveralls

    after-steps:
        - script:
            name: test after steps
            code: echo "Hello after-steps"

        - sherzberg/slack-notify:
            subdomain: g3-develop
            token: $SLACK_TOKEN
            channel: "#notification"
            username: wercker_build
```

This worked successfully [15 days ago]
![2016-10-27 13 11 40](https://cloud.githubusercontent.com/assets/5797788/19754440/84fc4be8-9c48-11e6-9603-8847d3d4c178.png)

This did not work [15 days ago]
![2016-10-27 13 12 12](https://cloud.githubusercontent.com/assets/5797788/19754448/91c50428-9c48-11e6-928e-7bbdf8998de7.png)
