### ISSUE TITLE
wercker.yml DSL

### ISSUE THREAD

**Issue by calvn** [wercker/wercker#258]
Is the `wercker.yml` in [the kubernetes example](https://github.com/wercker/wercker-kubernetes-quay/blob/master/wercker.yml#L39-L62) outdated? 

AFAIK `initialize` and `rolling-update` is not part of the DSL, but it is on the same level as `steps`. Running the `deploy` pipeline simply skips the kubectl-related steps.

**Comment by calvn** [comment]
So in linked example, both `initialize` and `rolling-update` will (both and always) trigger whenever the `deploy` pipeline is ran? Those are simply fancy names in lieu of `steps`?

**Comment by hatchan** [comment]
They will be run when the "Name" of the pipeline (on app.wercker.com) matches the `initialize` or `rolling-update` _and_ the "YML Pipeline Name" matches `deploy`. Basically `steps` is used for the fallback when nothing matches.

However you should avoid this and move `initialize` and `rolling-update` to the root (and add a steps section). As the other way is just there to support migrated applications, and might be removed in the future.

**Comment by calvn** [comment]
```yml
deploy:
    box: google/golang
    steps:
    # use the scratch step to build a container from scratch based on the files present
    - internal/docker-scratch-push:
        username: $QUAY_USERNAME
        password: $QUAY_PASSWORD
        cmd: ./app
        tag: $WERCKER_GIT_COMMIT
        ports: "5000"
        repository: quay.io/wercker/wercker-kubernetes-quay
        registry: https://quay.io

# Run this to create the rc and service
initialize:
    box: google/golang
    steps:
    - kubectl:
        server: $KUBERNETES_MASTER
        username: $KUBERNETES_USERNAME
        password: $KUBERNETES_PASSWORD
        insecure-skip-tls-verify: true
        command: create -f cities-controller.json

    - kubectl:
        server: $KUBERNETES_MASTER
        username: $KUBERNETES_USERNAME
        password: $KUBERNETES_PASSWORD
        insecure-skip-tls-verify: true
        command: create -f cities-service.json

# Update the replica controller to $WERCKER_GIT_COMMIT
rolling-update:
    box: google/golang
    steps:
    - kubectl:
        server: $KUBERNETES_MASTER
        username: $KUBERNETES_USERNAME
        password: $KUBERNETES_PASSWORD
        insecure-skip-tls-verify: true
        command: rolling-update cities
        image: quay.io/wercker/wercker-kubernetes-quay:$WERCKER_GIT_COMMIT
```

You're suggesting that it could have been written as such?
