### ISSUE TITLE
sentcli shouldn't do clear screen when logging into container

### ISSUE THREAD

**Issue by faiq** [wercker/wercker#26]
_From @flenter on December 21, 2015 8:46_

This is especially relevant when using `--attach-on-error` since the error message isn't visible anymore.

_Copied from original issue: wercker/sentcli#632_

**Comment by faiq** [comment]
_From @termie on January 15, 2016 19:31_

we dump quite a lot of env vars into the environment right before it gets to the shell, so it's a bit ugly, but sure

**Comment by faiq** [comment]
_From @termie on January 15, 2016 19:48_

ftr the error isn't printed in there, i think if you just scroll up you will see it even with the clear command, could you check that?

**Comment by faiq** [comment]
so i added this step to do some testing

```
clear:
  steps:
    - script:
        name: clear out the build binaries
        code: |
            echo "this shouldnt be clean!!!!!!"
            exit 1
```

and even when i left the `clean` command in, i was still able to scroll up and view the line that i `echo`'d
