### ISSUE TITLE
Guest command failed with exit code 1: mkdir -p "/pipeline"

### ISSUE THREAD

**Issue by cswarth** [wercker/wercker#262]
I don't know if this bug belongs here or in [ContinuumIO/docker-images](https://github.com/ContinuumIO/docker-images)

Short story:
The container [continuumio/conda_builder_linux](https://hub.docker.com/r/continuumio/conda_builder_linux/)  creates a user account 'dev' that does not have permission to write to the root of the container.  Wercker CLI assumes it can create '/pipeline' in any container it starts.  Ergo Wercker CLI cannot use [continuumio/conda_builder_linux](https://hub.docker.com/r/continuumio/conda_builder_linux/) 

I don't know yet whether this problem is unique to the CLI or also affects CI builds in the cloud as well.

Is there a workaround that would allow me to use the [continuumio/conda_builder_linux](https://hub.docker.com/r/continuumio/conda_builder_linux/) container with Wercker?

Long Story:

When I run a minimal "hello world" wercker file based on [continuumio/conda_builder_linux](https://hub.docker.com/r/continuumio/conda_builder_linux/) using the wercker CLI, it fails like so:

```
$ wercker build
--> No Docker host specified, checking: /var/run/docker.sock
--> Executing pipeline
--> Running step: setup environment
Pulling from continuumio/conda_builder_linux: latest
Digest: sha256:2c7993542e05cbb792d69eafeb8189cc141d59b3727070840d25ca25cf1ca9f0
Status: Image is up to date for continuumio/conda_builder_linux:latest
--> Copying source to container
ERROR --> Step failed: setup environment 2.40s
Guest command failed with exit code 1: mkdir -p "/pipeline"
ERROR Guest command failed with exit code 1: mkdir -p "/pipeline"
FATAL Exiting.
```

The same wercker.yml file based on on [continuumio/miniconda](https://hub.docker.com/r/continuumio/miniconda/) works fine.
```
$ wercker build
--> No Docker host specified, checking: /var/run/docker.sock
--> Executing pipeline
--> Running step: setup environment
Pulling from continuumio/miniconda: latest
Digest: sha256:6d6513477147178f0ca930020f7debdfcc42fd6ebd0c6e68da275f2a12aee733
Status: Image is up to date for continuumio/miniconda:latest
--> Copying source to container
--> Running step: wercker-init
--> Running step: script
hello, world
--> Steps passed: 2.85s
--> Pipeline finished: 3.86s
```

Exploring with docker shows the problem,
```
$ docker run -it --rm continuumio/conda_builder_linux /bin/bash
[dev@6f2bba0eeec2 ~]$ whoami 
dev
[dev@6f2bba0eeec2 ~]$ mkdir -p "/pipeline"
mkdir: cannot create directory `/pipeline': Permission denied
```

My minimal `wercker.yml` file
```
box: continuumio/conda_builder_linux

build:
  steps:
    - script:
        code: |
          echo "hello, world"
```

**Comment by cswarth** [comment]
I just discovered this issue is a more expansive duplicate of #229 which is a duplicate of @28.

Oh well, guess this is not gonna get fixed.

**Comment by Unode** [comment]
@cswarth Also ran into this problem while trying out an Alpine Linux container.
The [Alpine FAQ](http://devcenter.wercker.com/docs/faq/alpine-faq) somehow helped bypassing the same error you describe but then ran into #282.

**Comment by fruitl00p** [comment]
I just ran into this as well...

My situation is as follows
```yml
box: nginx:stable-alpine
build:
  steps:
    - script:
        name: echo nginx information
        code: nginx -v
    - script:
        name: copy the config
        code: cp resources/proxy.conf /etc/nginx/conf.d/default.conf
    - script:
        name: test nginx config
        code: nginx -t
    - script:
        name: dump nginx config
        code: nginx -T
```
Basically it builds an nginx confi and checks it... 

This too failed with the ```ERROR Guest command failed with exit code 1: mkdir -p "/pipeline"``` changing my box to ```nginx:stable``` works just fine though... (trial and error)

**Comment by fruitl00p** [comment]
After getting feedback from @wercker itself... I had my issue fixed:
```yml
box:
  id: nginx:stable-alpine
  cmd: /bin/sh
build:
  steps:
    - script:
        name: echo nginx information
        code: nginx -v
    - script:
        name: copy the config
        code: cp resources/proxy.conf /etc/nginx/conf.d/default.conf
    - script:
        name: test nginx config
        code: nginx -t
    - script:
        name: dump nginx config
        code: nginx -T
```

Works like a charm!
