### ISSUE TITLE
internal/docker-push step: push to ECR fails

### ISSUE THREAD

**Issue by Hashfyre** [wercker/wercker#291]
step definition:
```
      - internal/docker-push:
          disable-sync: false
          aws-access-key: $AWS_ACCESS_KEY_ID
          aws-secret-key: $AWS_SECRET_ACCESS_KEY
          aws-region: $AWS_REGION
          aws-registry-id: $AWS_REGISTRY_ID # set to <account-id>
          aws-strict-auth: true
          registry: https://<our-account-id>.dkr.ecr.<our-aws-region>.amazonaws.com/v2
          repository: test
          entrypoint: /entrypoint.sh
          ports: 80/tcp
          working-dir: /app/
          tag: WERCKER_STARTED_BY, $WERCKER_GIT_BRANCH, WERCKER_GIT_COMMIT
```

Given IAM permissions:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "Stmt#############",
            "Effect": "Allow",
            "Action": [
                "ecr:CompleteLayerUpload",
                "ecr:DescribeRepositories",
                "ecr:GetAuthorizationToken",
                "ecr:GetDownloadUrlForLayer",
                "ecr:GetRepositoryPolicy",
                "ecr:InitiateLayerUpload",
                "ecr:ListImages",
                "ecr:PutImage",
                "ecr:UploadLayerPart",
                "ecr:BatchCheckLayerAvailability",
                "ecr:BatchGetImage"
            ],
            "Resource": [
                "*"
            ]
        }
    ]
}
```

Expected Behavior:
 - successful auth and push to ECR

Actual Behavior:
```
Error interacting with this repository: test No Token found
```

Identified flow as discussed with @faiq:

```
wercker/wercker: 
docker.go: 
InitEnv(...)
  auther, _ := dockerauth.GetRegistryAuthenticator(opts)
  s.authenticator = auther
    -> auth-helper.go: 
        GetRegistryAuthenticator(...)
      -> auth.NewAmazonAuth(...)
```
Which calls functions from the dependecy,
```
wercker/docker-check-access: 
        -> amazon-auth.go: 
             NewAmazonAuth(...)
               -> Password(...)
                 -> getAuthToken(...)
                   -> svc.GetAuthorizationToken(...)
```
The above chain should ensure the `s.authenticator` gets all data it needs along with the ECR auth token.

The `authenticator` is the used as below:
```
wercker/wercker: 
docker.go:
Execute(...)
  	if !s.dockerOptions.DockerLocal {
		check, err := s.authenticator.CheckAccess(s.repository, auth.Push)
		if err != nil {
			s.logger.Errorln("Error interacting with this repository:", s.repository, err)
			return -1, fmt.Errorf("Error interacting with this repository: %s %v", s.repository, err)
		}
               ...
	}
```
This is where the first part of the error originates.

However, do notice the second part of the Error message: `No Token Found`, 
this is not part of:
  `amazon-auth.go: func (a *AmazonAuth) getAuthToken()`
  here: https://github.com/wercker/docker-check-access/blob/master/amazon-auth.go#L95
as it should be.
But rather part of:
  `docker-auth.go: func (d *DockerAuth) getToken(realm, service, scope string)`
  here: https://github.com/wercker/docker-check-access/blob/506de4f171b786ade70ae06badf6bffe7f48c123/docker-auth.go#L202

So, somehow in 
```
wercker/docker-check-access:
auth_helper.go:
func GetRegistryAuthenticator(opts CheckAccessOptions) (auth.Authenticator, error)
```
which selects between `NewAmazonAuth(...)`, `NewAzureAuth(...)` and `NewDockerAuth(...)`
`NewDockerAuth(...)` is getting executed in stead of `NewAmazonAuth(...)`

I'm trying to dig deeper and solve this issue, but some perspective would be nice.
