### ISSUE TITLE
CMD always overridden

### ISSUE THREAD

**Issue by hobti01** [wercker/wercker#293]
Is it expected behaviour that using box will always override the command specified in the image?
What is the correct strategy for reinstating the original command without manually inspecting the upstream image and copying this to the pipeline?

For example, the `CMD` of the nginx image is replaced with `/bin/bash`, but never reset to its original value of `nginx -g "daemon off;"`
```
my-pipeline:
  box:
    id: nginx

  steps:
    - internal/docker-push:
      username: $U
      password: $P
      repository: my-repo/my-nginx
```

This works to manually reset the original CMD, but surely this is not the expected pattern?
```
my-pipeline:
  box:
    id: nginx

  steps:
    - internal/docker-push:
      username: $U
      password: $P
      repository: my-repo/my-nginx
      cmd: nginx -g "daemon off;"
```
