### ISSUE TITLE
internal/docker-push and multiple env

### ISSUE THREAD

**Issue by quynhdang-vt** [wercker/wercker#341]
The documentation at http://devcenter.wercker.com/docs/steps/internal-steps mentioned this:

```
env - A list of environment variables in the form of "VAR=value","VAR2=value2". Can be delimited by spaces or commas.
```

I can not get this to work.  The docker image ends up with just one single image with value to be a combination of all the text after the first =.

Can you give an example of how to define multiple env variables for the container?

Thanks

**Comment by quynhdang-vt** [comment]
I got multiple environment variables to work by using spaces, not commas, e.g something like this

```
   - internal/docker-push:
        name: Pushing to Docker hub
        username: xxx
        password: xxx
        repository: xxx/yyyy
        tag: $MYTAG
        registry: https://registry.hub.docker.com
        working-dir: /app
        entrypoint: "/app/app.sh"
        env: '"VAR=value1" "ENV_APP_HOME=/app" "CONFIG_FILE=abce" "ENV_TYPE=$xxx_ENV_TYPE"'

```
