### ISSUE TITLE
After-steps aren't being reported when running in the cloud

### ISSUE THREAD

**Issue by flenter** [wercker/wercker#46]
It happens when the run fails.

Here's an example wercker.yml:

``` yaml
box: node:4.1.2
build:
  steps:
    - script:
        name: run test
        code: |
          fail_now
  after-steps:
      - script:
          name: after
          code: |
              echo "after"
              echo $WERCKER_RESULT
              echo "---"
```

I am unsure whether this is an issue for reporter-client specific or wercker/wercker.
