### ISSUE TITLE
issue with WERCKER_GIT_COMMIT

### ISSUE THREAD

**Issue by leeadh** [wercker/wercker#510]
Im trying to apply an update to a service I have. my Wercker file looks like this

```
# The container definition we want to use for developing our appss
box:
  id: node:latest
  ports:
    - "3000"

# Build definition
build:
  steps:
    - script:
        name: A step that executes `npm install`
        code: 
          npm install

    - script:
        name: echo nodejs information
        code: |
          echo "node version $(node -v) running"
          echo "npm version $(npm -v) running"
#Push the docker image with our built and tested application onto Docker Hub
push-to-dockerhub:
    steps:
      # Push to public docker repo
      - internal/docker-push:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD
          tag: $WERCKER_GIT_COMMIT
          repository: leexha/nodejsapp
          registry: https://index.docker.io/v2/
          cmd: node /pipeline/source/sampleApp.js

#
deploy-to-kuberntes:
    steps:
      - kubectl: 
          name: apply deployment
          server: $KUBERNETES_MASTER
          token: $KUBERNETES_TOKEN
          insecure-skip-tls-verify: true
          command: apply -f ./deploy.yml
      
      - kubectl:
          name: apply service
          server: $KUBERNETES_MASTER
          token: $KUBERNETES_TOKEN
          insecure-skip-tls-verify: true
          command: apply -f ./service.yml
        
```

and my deployment file looks like this:

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mynodejsapp
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: leexha/nodejsapp:$WERCKER_GIT_COMMIT
        ports:
        - containerPort: 3000
        resources:
          requests: 
            memory: 500Mi
            cpu: 0.5
          limits:
            memory: 500Mi
            cpu: 0.5
        imagePullPolicy: Always

```
It keeps saying that on the k8s cluster that its piulling the leexha/nodejsapp:$WERCKER_GIT_COMMIT instead of the actual hash. 

What am I doing wrong? I tried a few permutations and I still cant resolve this
