### ISSUE TITLE
Ensure that internal/docker-push interpolates env vars BEFORE splitting tags

### ISSUE THREAD

**Issue by yuki-takei** [wercker/wercker#540]
# Current Behavior

When we have following steps:

```
steps:

  - script:
    code: export TAGS_TO_PUSH=tag1, tag2, tag3

  - internal/docker-push:
    tag: latest, $TAGS_TO_PUSH

```

`validateTags` occures an error like

> Invalid tag: tag1,tag2, tag3: invalid tag format

## Cause

- Interpolation is processed AFTER splitting tags.
- https://github.com/wercker/wercker/blob/1.0.1421/docker/docker.go#L468

# Expected Behavior

- Interpolation is processed BEFORE splitting tags.
