### ISSUE TITLE
wercker build panics: slice bounds out of range

### ISSUE THREAD

**Issue by kszafran** [wercker/wercker#555]
I have the following `wercker.yml` file:
```yaml
build:
  box: openjdk:8-jre
  steps:
    - script:
      name: Schedule cronjob
      code: ./bin/setup.sh
    - internal/store-container:
      working-dir: /pipeline/source
      tag: latest,$WERCKER_GIT_BRANCH,$WERCKER_GIT_COMMIT
      labels:
        - "PROJECT=$WERCKER_GIT_REPOSITORY"
        - "COMMIT=$WERCKER_GIT_COMMIT"
```

The first few builds were successful (or failed due to mistakes in setup.sh), but then wercker-cli stopped working. This is the error that I'm getting:
```
$ wercker build
--> No Docker host specified, checking: /var/run/docker.sock
--> Executing pipeline: build
--> Copying working directory to: [removed]
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
github.com/wercker/wercker/cmd.(*Runner).CleanupOldBuilds(0xc4200ba280, 0xc420210300, 0x53)
	/go/src/github.com/wercker/wercker/cmd/runner.go:266 +0x5a2
github.com/wercker/wercker/cmd.executePipeline(0x28b2098, 0xc42022c630, 0xc4200c86c0, 0xc42050c160, 0xc420114600, 0x0, 0x0, 0x0)
	/go/src/github.com/wercker/wercker/cmd/main.go:1134 +0x582
github.com/wercker/wercker/cmd.cmdBuild(0x28b2060, 0xc4200320c0, 0xc4200c86c0, 0xc42050c160, 0xc42021e3f0, 0xc42050c160, 0x0)
	/go/src/github.com/wercker/wercker/cmd/main.go:610 +0xc2
github.com/wercker/wercker/cmd.glob..func1(0xc420480000)
	/go/src/github.com/wercker/wercker/cmd/main.go:71 +0x3ff
github.com/wercker/wercker/vendor/gopkg.in/urfave/cli%2ev1.HandleAction(0x1b0b040, 0x1d70b38, 0xc420480000, 0xc420206200, 0x0)
	/go/src/github.com/wercker/wercker/vendor/gopkg.in/urfave/cli.v1/app.go:492 +0x7c
github.com/wercker/wercker/vendor/gopkg.in/urfave/cli%2ev1.Command.Run(0x1d1d4ab, 0x5, 0x1d1ba1e, 0x1, 0x0, 0x0, 0x0, 0x1d28cbd, 0xf, 0x0, ...)
	/go/src/github.com/wercker/wercker/vendor/gopkg.in/urfave/cli.v1/command.go:210 +0xa36
github.com/wercker/wercker/vendor/gopkg.in/urfave/cli%2ev1.(*App).Run(0xc42041e680, 0xc42000a060, 0x2, 0x2, 0x0, 0x0)
	/go/src/github.com/wercker/wercker/vendor/gopkg.in/urfave/cli.v1/app.go:255 +0x6a0
main.main()
	/go/src/github.com/wercker/wercker/main.go:25 +0x4b
```

I'm using wercker-cli 1.0.1467 (I had the same issue with 1.0.1323) on macOS Mojave 10.14.2.

A workaround is to delete`.wercker/` which allows me to run builds again.
