### ISSUE TITLE
docker-compose support?

### ISSUE THREAD

**Issue by djMax** [wercker/wercker#63]
I have a variety of modules and micro services that I run though wercker. They rely on consul, postgres, logstash, rabbitmq, etc. I could of course mock all these things out, but for me I'd rather run tests that look more like the real thing (not trying to get into a unit test flame war here). So right now I have to basically copy that boilerplate services and steps to set them up rather than just using my compose file or at least super similar syntax.

**Comment by chiefy** [comment]
I recently had an issue using Elasticsearch as a service w/ wercker. I spent some time trying to figure it out (it was randomly shutting down after 3-10 minutes, TRACE logging didn't even help expose what the issue is). I switched our team back over to using docker-compose. It'd be awesome if you could potentially flag the `wercker.yml` `dev` pipeline to defer to use `docker-compose`. I still think that the `build` and `deploy` pipelines are awesome to use with CI/CD - it's just the local dev experience that is a little flawed.

**Comment by chiefy** [comment]
```
dev:
  use_compose: true
  app:
    image: something/somewhere:latest
    command: /path/to/service/run.sh
  service:
   environment:
      MY_ENV_VAR: hansgruber
   ports:
     - "8000:9200"

build:
...
```

**Comment by shehi** [comment]
@chiefy : We shouldn't be copying docker-compose.yml file content again into wercker.yml. Instead, Wercker should be looking for the file and adjusting itself accordingly. Additionally, we should be able to provide custom docker-compose.yml file location for different env setups. E.g.:

https://github.com/AudithSoftworks/Basis/blob/master/docker-compose-hhvm.yml

vs

https://github.com/AudithSoftworks/Basis/blob/master/docker-compose-php56.yml

**Comment by chiefy** [comment]
@shehi sorry, that's exactly what I was saying :+1:

**Comment by elhachmi** [comment]
This is already on the road map for the upoming versions?

**Comment by rjferguson21** [comment]
I would love if we could leverage the existing docker-compose syntax for describing what you call today as wercker services.  Would be great to employ docker-compose best practices instead of reinventing the wheel with wercker services.

**Comment by lowks** [comment]
Definitely need this too!

**Comment by djMax** [comment]
I suppose the other option is that docker support some sort of "render this docker-compose file to a single container"... Which would be cool.

**Comment by robhaswell** [comment]
For our organisation, the integration tests which developers run on their laptops are defined as `docker-compose` apps. For example, we might have a NodeJS app which speaks to a database which is also shipped as a container. The developer runs the test suite with:

`docker-compose run --rm app npm test`

Our `docker-compose.yml` file might look like:

```yml
version: '2'
services:
  app:
    build: .
    links:
      - db
  db:
    image: myorg/db
```

I am currently in the process of selecting a build system which will allow us to continue with this workflow.
