### ISSUE TITLE
Enable TTY during build

### ISSUE THREAD

**Issue by jakirkham** [wercker/wercker#95]
Sometimes installation of dependencies assumes that a TTY is configured. While this is not always the case, it is not always possible to configure the installer to not use one. Would it be possible to expose Docker's `-t` and possibly `-i`, as well, or is this already possible?

**Comment by lukaf** [comment]
Not sure if this helps, but I'm using [script](http://man7.org/linux/man-pages/man1/script.1.html) to run a command that needs a tty to work properly:

```
build:
  steps:
    - script:
      name: something that needs tty
      code: script -qfc "command" | cat
```
